### ISSUE TITLE
shader doesn't work in 1.19.2 forge oculus

### ISSUE THREAD

**Issue by loti1234** [Despatra/Phoxel#12]
the shader doesn't work at all
**Steps to Reproduce**
enable shader while having oculus installed in 1.19.2

**Screenshots**
with shader:
![image](https://github.com/Despatra/Phoxel/assets/140719665/01a5df36-6060-44c4-b485-ec6463138492)
without shader:
![image](https://github.com/Despatra/Phoxel/assets/140719665/a9bcd2b6-1a8a-49ac-961e-7fface289f52)

 - Minecraft Version: 1.19.2
 - Shader Version: 0.4.0.3
 - Shader Loader: [Oculus]

**Comment by Despatra** [comment]
Well the shader doesn't say it's compatible with 1.19.2, I've tried it on 1.20.1 and it works fine, but you also have some mods. So I would update your game if at all possible and try that, if it still doesn't work then there may be incompatible mods too.

**Comment by loti1234** [comment]
it isn't cuz of incompat mods and it also does work for me in 1.20.1 so its an oculus skill issue cuz of it not getting updated stuffs phoxel uses

**Comment by Despatra** [comment]
glad to know that fixed it!
