### ISSUE TITLE
broken light emission

### ISSUE THREAD

**Issue by SJK9906** [Despatra/Phoxel#13]
**Describe the bug**
sours light emit light only if (and):
- a BPR resourspack is loaded
- light sours is visible on the screen
amage is very noisy

**Steps to Reproduce**
1. create a new world
2. place a sour light (ex: a torch)
3. if you don't see the torch in the screen it don't emit light

**Screenshots**
![image](https://github.com/Despatra/Phoxel/assets/129201282/af38a9d9-7d41-47e8-9b6d-628a4619317d)
![image](https://github.com/Despatra/Phoxel/assets/129201282/d346fad7-5d25-4df5-abb2-43cc34fa202d)
![Uploading image.png…]()

**Specifications if it has to do with performance or crashes**
 - Graphics Card:  RTX 3060 - Minecraft Version: 1.21 java, iris 1.7.2, fabric 0.15.11, sodium 0.5.11
 - Shader Version:  0.4.0.3
 - Shader Loader:  iris

**Additional context**
world: [New World.zip](https://github.com/user-attachments/files/16049951/New.World.zip)
PBR resourpack: [ultimacraft-pbr-modded-b-0-1.zip](https://github.com/user-attachments/files/16049970/ultimacraft-pbr-modded-b-0-1.zip)
logs: [latest.log](https://github.com/user-attachments/files/16049959/latest.log)
shader config: [Phoxel Beta 0.4.0.3.zip.txt](https://github.com/user-attachments/files/16050017/Phoxel.Beta.0.4.0.3.zip.txt)

**Comment by Despatra** [comment]
These are known and having to have a PBR pack will be fixed in the next update with integrated PBR. IDK when I will get around to explicitly sampling block lights though, which is the only way to reduce the noise here.
