### ISSUE TITLE
GL_ARB_Image_Size extension unsupported

### ISSUE THREAD

**Issue by nomeat1997** [Despatra/Phoxel#15]
**Describe the bug**

Shaderpack failed to load

**Steps to Reproduce**
*if you can

**Screenshots**
*If applicable*

**Specifications if it has to do with performance or crashes**
 - Graphics Card: AMD RX580
 - Minecraft Version: 1.21
 - Shader Version: Current version as of writing in https://modrinth.com/shader/phoxel
 - Shader Loader: Iris

**Additional context**

prepare.fsh: prepare.fsh: ERROR: 0:32: 'imageSize' : no matching overloaded function found 
ERROR: 0:32: '=' :  cannot convert from ' const float' to ' global 2-component vector of int'
ERROR: 0:32: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.

**Comment by Despatra** [comment]
I would double check that your drivers are up to date and that your system supports GLSL 430 or greater.

**Comment by nomeat1997** [comment]
I confirm that I have the latest drivers for the card. (24.3.1)
This card supports OpenGL 4.6, this should be enough for GLSL 430, right ?

[opengl.txt](https://github.com/user-attachments/files/16170601/opengl.txt)

**Comment by Despatra** [comment]
Imagesize() should no longer be needed.
