### ISSUE TITLE
Request: Auto Exposure and lighting balance

### ISSUE THREAD

**Issue by MrSzalonna** [Despatra/Phoxel#16]
**Describe what you want added/removed/changed**
Hey! I noticed that the torches are very weak in the picture mode.
Here is a picture I took in the stronghold after 10 minutes of waiting.
![2024-07-31_22 31 27](https://github.com/user-attachments/assets/a6d77cc9-e108-4ff0-8056-43dd946c1ae1)
You can clearly see that the torches couldn't light up the room.
![2024-07-31_21 59 14](https://github.com/user-attachments/assets/8bf3c7b2-4102-488c-811a-839cfa04e558)
While it's not on max brightness, other things light up pretty well.
PBR texture pack: UltimaCraft PBR.
Thank you for your beautiful shader.
Edit: I think a cheap auto exposure setting would be good.

**Comment by Despatra** [comment]
Hello thank you for the compliment!, Unfortunately this low brightness is because of incorrect voxelization, which is a known issue. And auto exposure will be coming in the next update!
