### ISSUE TITLE
Bug Report: Vegetation shadows don't work as intended.

### ISSUE THREAD

**Issue by MrSzalonna** [Despatra/Phoxel#17]
**Describe the bug**
1. Grass, tall grass and flowers won't stop the light. This means that they won't cast a shadow.
2. The bush stops the light, but in a wrong way (like a block would do)

**Steps to Reproduce**
Plant a grass, tall grass or any type of flower.

**Screenshots**
![2024-08-03_19 23 45](https://github.com/user-attachments/assets/22315234-0a06-4b24-b712-39b4b37a587a)
![2024-08-03_19 25 44](https://github.com/user-attachments/assets/add77bb1-6130-4b87-89c5-85ebc91cba62)
![2024-08-03_19 26 42](https://github.com/user-attachments/assets/1674cf86-8940-4026-8ad8-d6e04156def1)
![2024-08-03_19 27 13](https://github.com/user-attachments/assets/c4ee226a-63ba-409e-9824-f27a24baed11)
![2024-08-03_19 28 40](https://github.com/user-attachments/assets/2b6f8d98-f827-4092-9e2d-579c4de23617)

**Specifications if it has to do with performance or crashes**
 - Graphics Card: Nvidia GeForce RTX 4080
 - Minecraft Version: 1.21 (Fabric with a ton of mods)
 - Shader Version: Latest (0.4.0.3)
 - Shader Loader: Iris 1.7.3

**Additional context**
Texture packs: Connected stuff, Vanilla tweaks (not anything vegetation releated), UltimaCraft PBR (works with other shaders)

Sorry for the many reports, but I'm testing a lot with this shader. Also please improve on the denoising because that doesn't work well. :) Thanks!

**Comment by Despatra** [comment]
Until the total voxelization update anything that is not a full block will have to either be treated as such or as if it doesn't exist at all shadow and reflection wise.

**Comment by Despatra** [comment]
Since this is already an issue I have listed under "Incorrect Voxelization" I will close this issue.

**Comment by Despatra** [comment]
and about the denoising I have improvements coming and you can turn of Temporal Accumulation in the shaderpack settings > path tracer. I need all the feedback I can get so don't sweat it!
