### ISSUE TITLE
Bug Report: The lily pad's lighting is glitched.

### ISSUE THREAD

**Issue by MrSzalonna** [Despatra/Phoxel#18]
**Describe the bug**
The area arount the lily pad doesn't have lightning.
**Steps to Reproduce**
Place a lily pad in a bigger pond.

**Screenshots**
![file](https://github.com/user-attachments/assets/a8aa4fd3-173f-44d0-aa70-ed9b674a2e5a)

**Specifications if it has to do with performance or crashes**
 - Graphics Card: Nvidia GeForce RTX 4080
 - Minecraft Version: 1.21
 - Shader Version: 0.4.03
 - Shader Loader: Iris 0.7.3

**Additional context**
Sorry for this many bug reports, but I just find them. I hope I helped you. Thanks again for this piece of art.

**Comment by Despatra** [comment]
This is fixed in the upcoming patch
