### ISSUE TITLE
Incorrect intersection (White line in between the blocks in reflection)

### ISSUE THREAD

**Issue by MrSzalonna** [Despatra/Phoxel#19]
**Describe the bug**
The title is confusing I know. When you look at the white or light colored block and its reflection, you'll see a weird line in between the blocks.

**Steps to Reproduce**
Place white concrete next to water and look at the hardened clay and the water.

**Screenshots**
![file (1)](https://github.com/user-attachments/assets/4f634261-eecf-401b-bbed-e55cdc79fba7)

**Specifications if it has to do with performance or crashes**
 - Graphics Card: 4080
 - Minecraft Version: 1.21
 - Shader Version: 0.4.0.3
 - Shader Loader: Iris

**Additional context**
Oh my God please no more. BTW are the reflections screen-space or not? I'm trying to help you. Thanks!

**Comment by Despatra** [comment]
They are screen-space unless it's not on screen. There are texture issues and I bet that is what you're seeing here. I'm working on a fix.

**Comment by Despatra** [comment]
Hey!, does this still happen with the newest update for you?
