### ISSUE TITLE
toch light

### ISSUE THREAD

**Issue by SK-9906** [Despatra/Phoxel#22]
**Describe the bug**
torch doesn't emit light

**Steps to Reproduce**
1. open a world
2. place a toch

**Screenshots**
*If applicable*
<img width="960" alt="{8F760DD3-EEDF-428A-807A-718291AABAA0}" src="https://github.com/user-attachments/assets/d1306732-b769-46a9-8674-d30a00cd82ba">

**Comment by Despatra** [comment]
This is already an issue listed under Incorrect Voxelization.
