### ISSUE TITLE
composite.fsh: composite.fsh: 0:3(12): warning: extension GL_EXT_gpu_shader4 unsupported in fragment shader 0:25(8): error: unrecognized layout identifier rgba8

### ISSUE THREAD

**Issue by ThGrSoRu** [Despatra/Phoxel#7]
**Describe the bug**
Shaderpack fails to load immediately.

**Steps to Reproduce**
Enable the shaderpack.

**Screenshots**
Not relevant.

**Specifications if it has to do with performance or crashes**
 - OS: Arch Linux
 - Graphics Card: Radeon RX 6700 XT
 - Minecraft Version: 1.20.1
 - Shader Version: Beta 0.3.0
 - Shader Loader: Iris

**Additional context**
None.

**Comment by Despatra** [comment]
You can go into composite.fsh and just delete that line of code

**Comment by ThGrSoRu** [comment]
Deleting the line containing `GL_EXT_gpu_shader4` results in:
```
composite.fsh: composite.fsh: 0:24(8): error: unrecognized layout identifier `rgba8'
```
Incrementally deleting all lines containing `rgba8` results in the same previous error, with differing line numbers, until all are deleted:
<details><summary>Details</summary>
<p>
composite.fsh: composite.fsh: 0:98(27): warning: signed literal value `2891336453' is interpreted as -14036308430:67(27): error: `colorimg1' undeclared0:67(17): error: no matching function for call to `imageSize(error)'; candidates are:0:67(17): error:    int imageSize(image1D)0:67(17): error:    ivec2 imageSize(image2D)0:67(17): error:    ivec3 imageSize(image3D)0:67(17): error:    ivec2 imageSize(image2DRect)0:67(17): error:    ivec2 imageSize(imageCube)0:67(17): error:    int imageSize(imageBuffer)0:67(17): error:    ivec2 imageSize(image1DArray)0:67(17): error:    ivec3 imageSize(image2DArray)0:67(17): error:    ivec3 imageSize(imageCubeArray)0:67(17): error:    ivec2 imageSize(image2DMS)0:67(17): error:    ivec3 imageSize(image2DMSArray)0:67(17): error:    int imageSize(iimage1D)0:67(17): error:    ivec2 imageSize(iimage2D)0:67(17): error:    ivec3 imageSize(iimage3D)0:67(17): error:    ivec2 imageSize(iimage2DRect)0:67(17): error:    ivec2 imageSize(iimageCube)0:67(17): error:    int imageSize(iimageBuffer)0:67(17): error:    ivec2 imageSize(iimage1DArray)0:67(17): error:    ivec3 imageSize(iimage2DArray)0:67(17): error:    ivec3 imageSize(iimageCubeArray)0:67(17): error:    ivec2 imageSize(iimage2DMS)0:67(17): error:    ivec3 imageSize(iimage2DMSArray)0:67(17): error:    int imageSize(uimage1D)0:67(17): error:    ivec2 imageSize(uimage2D)0:67(17): error:    ivec3 imageSize(uimage3D)0:67(17): error:    ivec2 imageSize(uimage2DRect)0:67(17): error:    ivec2 imageSize(uimageCube)0:67(17): error:    int imageSize(uimageBuffer)0:67(17): error:    ivec2 imageSize(uimage1DArray)0:67(17): error:    ivec3 imageSize(uimage2DArray)0:67(17): error:    ivec3 imageSize(uimageCubeArray)0:67(17): error:    ivec2 imageSize(uimage2DMS)0:67(17): error:    ivec3 imageSize(uimage2DMSArray)0:94(28): warning: `imgSize' used uninitialized0:94(44): warning: `imgSize' used uninitialized0:95(18): error: `colorimg1' undeclared0:95(8): error: no matching function for call to `imageLoad(error, ivec2)'; candidates are:0:95(8): error:    vec4 imageLoad(image1D, int)0:95(8): error:    vec4 imageLoad(image2D, ivec2)0:95(8): error:    vec4 imageLoad(image3D, ivec3)0:95(8): error:    vec4 imageLoad(image2DRect, ivec2)0:95(8): error:    vec4 imageLoad(imageCube, ivec3)0:95(8): error:    vec4 imageLoad(imageBuffer, int)0:95(8): error:    vec4 imageLoad(image1DArray, ivec2)0:95(8): error:    vec4 imageLoad(image2DArray, ivec3)0:95(8): error:    vec4 imageLoad(imageCubeArray, ivec3)0:95(8): error:    vec4 imageLoad(image2DMS, ivec2, int)0:95(8): error:    vec4 imageLoad(image2DMSArray, ivec3, int)0:95(8): error:    ivec4 imageLoad(iimage1D, int)0:95(8): error:    ivec4 imageLoad(iimage2D, ivec2)0:95(8): error:    ivec4 imageLoad(iimage3D, ivec3)0:95(8): error:    ivec4 imageLoad(iimage2DRect, ivec2)0:95(8): error:    ivec4 imageLoad(iimageCube, ivec3)0:95(8): error:    ivec4 imageLoad(iimageBuffer, int)0:95(8): error:    ivec4 imageLoad(iimage1DArray, ivec2)0:95(8): error:    ivec4 imageLoad(iimage2DArray, ivec3)0:95(8): error:    ivec4 imageLoad(iimageCubeArray, ivec3)0:95(8): error:    ivec4 imageLoad(iimage2DMS, ivec2, int)0:95(8): error:    ivec4 imageLoad(iimage2DMSArray, ivec3, int)0:95(8): error:    uvec4 imageLoad(uimage1D, int)0:95(8): error:    uvec4 imageLoad(uimage2D, ivec2)0:95(8): error:    uvec4 imageLoad(uimage3D, ivec3)0:95(8): error:    uvec4 imageLoad(uimage2DRect, ivec2)0:95(8): error:    uvec4 imageLoad(uimageCube, ivec3)0:95(8): error:    uvec4 imageLoad(uimageBuffer, int)0:95(8): error:    uvec4 imageLoad(uimage1DArray, ivec2)0:95(8): error:    uvec4 imageLoad(uimage2DArray, ivec3)0:95(8): error:    uvec4 imageLoad(uimageCubeArray, ivec3)0:95(8): error:    uvec4 imageLoad(uimage2DMS, ivec2, int)0:95(8): error:    uvec4 imageLoad(uimage2DMSArray, ivec3, int)0:95(8): error: type mismatch0:95(8): error: operands of `!=' must have the same type0:98(8): warning: `Seed' used uninitialized0:104(19): error: `colorimg8' undeclared0:104(41): warning: `imgSize' used uninitialized0:104(57): warning: `imgSize' used uninitialized0:104(9): error: no matching function for call to `imageLoad(error, ivec2)'; candidates are:0:104(9): error:    vec4 imageLoad(image1D, int)0:104(9): error:    vec4 imageLoad(image2D, ivec2)0:104(9): error:    vec4 imageLoad(image3D, ivec3)0:104(9): error:    vec4 imageLoad(image2DRect, ivec2)0:104(9): error:    vec4 imageLoad(imageCube, ivec3)0:104(9): error:    vec4 imageLoad(imageBuffer, int)0:104(9): error:    vec4 imageLoad(image1DArray, ivec2)0:104(9): error:    vec4 imageLoad(image2DArray, ivec3)0:104(9): error:    vec4 imageLoad(imageCubeArray, ivec3)0:104(9): error:    vec4 imageLoad(image2DMS, ivec2, int)0:104(9): error:    vec4 imageLoad(image2DMSArray, ivec3, int)0:104(9): error:    ivec4 imageLoad(iimage1D, int)0:104(9): error:    ivec4 imageLoad(iimage2D, ivec2)0:104(9): error:    ivec4 imageLoad(iimage3D, ivec3)0:104(9): error:    ivec4 imageLoad(iimage2DRect, ivec2)0:104(9): error:    ivec4 imageLoad(iimageCube, ivec3)0:104(9): error:    ivec4 imageLoad(iimageBuffer, int)0:104(9): error:    ivec4 imageLoad(iimage1DArray, ivec2)0:104(9): error:    ivec4 imageLoad(iimage2DArray, ivec3)0:104(9): error:    ivec4 imageLoad(iimageCubeArray, ivec3)0:104(9): error:    ivec4 imageLoad(iimage2DMS, ivec2, int)0:104(9): error:    ivec4 imageLoad(iimage2DMSArray, ivec3, int)0:104(9): error:    uvec4 imageLoad(uimage1D, int)0:104(9): error:    uvec4 imageLoad(uimage2D, ivec2)0:104(9): error:    uvec4 imageLoad(uimage3D, ivec3)0:104(9): error:    uvec4 imageLoad(uimage2DRect, ivec2)0:104(9): error:    uvec4 imageLoad(uimageCube, ivec3)0:104(9): error:    uvec4 imageLoad(uimageBuffer, int)0:104(9): error:    uvec4 imageLoad(uimage1DArray, ivec2)0:104(9): error:    uvec4 imageLoad(uimage2DArray, ivec3)0:104(9): error:    uvec4 imageLoad(uimageCubeArray, ivec3)0:104(9): error:    uvec4 imageLoad(uimage2DMS, ivec2, int)0:104(9): error:    uvec4 imageLoad(uimage2DMSArray, ivec3, int)0:104(9): error: type mismatch0:106(22): error: `colorimg9' undeclared0:106(44): warning: `imgSize' used uninitialized0:106(60): warning: `imgSize' used uninitialized0:106(12): error: no matching function for call to `imageLoad(error, ivec2)'; candidates are:0:106(12): error:    vec4 imageLoad(image1D, int)0:106(12): error:    vec4 imageLoad(image2D, ivec2)0:106(12): error:    vec4 imageLoad(image3D, ivec3)0:106(12): error:    vec4 imageLoad(image2DRect, ivec2)0:106(12): error:    vec4 imageLoad(imageCube, ivec3)0:106(12): error:    vec4 imageLoad(imageBuffer, int)0:106(12): error:    vec4 imageLoad(image1DArray, ivec2)0:106(12): error:    vec4 imageLoad(image2DArray, ivec3)0:106(12): error:    vec4 imageLoad(imageCubeArray, ivec3)0:106(12): error:    vec4 imageLoad(image2DMS, ivec2, int)0:106(12): error:    vec4 imageLoad(image2DMSArray, ivec3, int)0:106(12): error:    ivec4 imageLoad(iimage1D, int)0:106(12): error:    ivec4 imageLoad(iimage2D, ivec2)0:106(12): error:    ivec4 imageLoad(iimage3D, ivec3)0:106(12): error:    ivec4 imageLoad(iimage2DRect, ivec2)0:106(12): error:    ivec4 imageLoad(iimageCube, ivec3)0:106(12): error:    ivec4 imageLoad(iimageBuffer, int)0:106(12): error:    ivec4 imageLoad(iimage1DArray, ivec2)0:106(12): error:    ivec4 imageLoad(iimage2DArray, ivec3)0:106(12): error:    ivec4 imageLoad(iimageCubeArray, ivec3)0:106(12): error:    ivec4 imageLoad(iimage2DMS, ivec2, int)0:106(12): error:    ivec4 imageLoad(iimage2DMSArray, ivec3, int)0:106(12): error:    uvec4 imageLoad(uimage1D, int)0:106(12): error:    uvec4 imageLoad(uimage2D, ivec2)0:106(12): error:    uvec4 imageLoad(uimage3D, ivec3)0:106(12): error:    uvec4 imageLoad(uimage2DRect, ivec2)0:106(12): error:    uvec4 imageLoad(uimageCube, ivec3)0:106(12): error:    uvec4 imageLoad(uimageBuffer, int)0:106(12): error:    uvec4 imageLoad(uimage1DArray, ivec2)0:106(12): error:    uvec4 imageLoad(uimage2DArray, ivec3)0:106(12): error:    uvec4 imageLoad(uimageCubeArray, ivec3)0:106(12): error:    uvec4 imageLoad(uimage2DMS, ivec2, int)0:106(12): error:    uvec4 imageLoad(uimage2DMSArray, ivec3, int)0:109(12): warning: `RayOrgn' used uninitialized0:109(29): warning: `RayOrgn' used uninitialized0:109(40): warning: `RayDir' used uninitialized0:121(14): warning: `RayOrgn' used uninitialized0:122(27): warning: `RayDir' used uninitialized0:123(37): warning: `RayDir' used uninitialized0:123(54): warning: `RayDir' used uninitialized0:123(71): warning: `RayDir' used uninitialized0:123(100): warning: `RayDir' used uninitialized0:141(10): warning: `RayDir' used uninitialized0:161(61): warning: `RayOrgn' used uninitialized0:201(148): warning: `PlayerView' used uninitialized0:244(28): error: `colorimg4' undeclared0:244(18): error: no matching function for call to `imageLoad(error, ivec2)'; candidates are:0:244(18): error:    vec4 imageLoad(image1D, int)0:244(18): error:    vec4 imageLoad(image2D, ivec2)0:244(18): error:    vec4 imageLoad(image3D, ivec3)0:244(18): error:    vec4 imageLoad(image2DRect, ivec2)0:244(18): error:    vec4 imageLoad(imageCube, ivec3)0:244(18): error:    vec4 imageLoad(imageBuffer, int)0:244(18): error:    vec4 imageLoad(image1DArray, ivec2)0:244(18): error:    vec4 imageLoad(image2DArray, ivec3)0:244(18): error:    vec4 imageLoad(imageCubeArray, ivec3)0:244(18): error:    vec4 imageLoad(image2DMS, ivec2, int)0:244(18): error:    vec4 imageLoad(image2DMSArray, ivec3, int)0:244(18): error:    ivec4 imageLoad(iimage1D, int)0:244(18): error:    ivec4 imageLoad(iimage2D, ivec2)0:244(18): error:    ivec4 imageLoad(iimage3D, ivec3)0:244(18): error:    ivec4 imageLoad(iimage2DRect, ivec2)0:244(18): error:    ivec4 imageLoad(iimageCube, ivec3)0:244(18): error:    ivec4 imageLoad(iimageBuffer, int)0:244(18): error:    ivec4 imageLoad(iimage1DArray, ivec2)0:244(18): error:    ivec4 imageLoad(iimage2DArray, ivec3)0:244(18): error:    ivec4 imageLoad(iimageCubeArray, ivec3)0:244(18): error:    ivec4 imageLoad(iimage2DMS, ivec2, int)0:244(18): error:    ivec4 imageLoad(iimage2DMSArray, ivec3, int)0:244(18): error:    uvec4 imageLoad(uimage1D, int)0:244(18): error:    uvec4 imageLoad(uimage2D, ivec2)0:244(18): error:    uvec4 imageLoad(uimage3D, ivec3)0:244(18): error:    uvec4 imageLoad(uimage2DRect, ivec2)0:244(18): error:    uvec4 imageLoad(uimageCube, ivec3)0:244(18): error:    uvec4 imageLoad(uimageBuffer, int)0:244(18): error:    uvec4 imageLoad(uimage1DArray, ivec2)0:244(18): error:    uvec4 imageLoad(uimage2DArray, ivec3)0:244(18): error:    uvec4 imageLoad(uimageCubeArray, ivec3)0:244(18): error:    uvec4 imageLoad(uimage2DMS, ivec2, int)0:244(18): error:    uvec4 imageLoad(uimage2DMSArray, ivec3, int)0:245(19): warning: `FrameData' used uninitialized0:253(19): warning: `FrameData' used uninitialized0:254(12): error: `colorimg4' undeclared0:254(1): error: no matching function for call to `imageStore(error, ivec2, vec4)'; candidates are:0:254(1): error:    void imageStore(image1D, int, vec4)0:254(1): error:    void imageStore(image2D, ivec2, vec4)0:254(1): error:    void imageStore(image3D, ivec3, vec4)0:254(1): error:    void imageStore(image2DRect, ivec2, vec4)0:254(1): error:    void imageStore(imageCube, ivec3, vec4)0:254(1): error:    void imageStore(imageBuffer, int, vec4)0:254(1): error:    void imageStore(image1DArray, ivec2, vec4)0:254(1): error:    void imageStore(image2DArray, ivec3, vec4)0:254(1): error:    void imageStore(imageCubeArray, ivec3, vec4)0:254(1): error:    void imageStore(image2DMS, ivec2, int, vec4)0:254(1): error:    void imageStore(image2DMSArray, ivec3, int, vec4)0:254(1): error:    void imageStore(iimage1D, int, ivec4)0:254(1): error:    void imageStore(iimage2D, ivec2, ivec4)0:254(1): error:    void imageStore(iimage3D, ivec3, ivec4)0:254(1): error:    void imageStore(iimage2DRect, ivec2, ivec4)0:254(1): error:    void imageStore(iimageCube, ivec3, ivec4)0:254(1): error:    void imageStore(iimageBuffer, int, ivec4)0:254(1): error:    void imageStore(iimage1DArray, ivec2, ivec4)0:254(1): error:    void imageStore(iimage2DArray, ivec3, ivec4)0:254(1): error:    void imageStore(iimageCubeArray, ivec3, ivec4)0:254(1): error:    void imageStore(iimage2DMS, ivec2, int, ivec4)0:254(1): error:    void imageStore(iimage2DMSArray, ivec3, int, ivec4)0:254(1): error:    void imageStore(uimage1D, int, uvec4)0:254(1): error:    void imageStore(uimage2D, ivec2, uvec4)0:254(1): error:    void imageStore(uimage3D, ivec3, uvec4)0:254(1): error:    void imageStore(uimage2DRect, ivec2, uvec4)0:254(1): error:    void imageStore(uimageCube, ivec3, uvec4)0:254(1): error:    void imageStore(uimageBuffer, int, uvec4)0:254(1): error:    void imageStore(uimage1DArray, ivec2, uvec4)0:254(1): error:    void imageStore(uimage2DArray, ivec3, uvec4)0:254(1): error:    void imageStore(uimageCubeArray, ivec3, uvec4)0:254(1): error:    void imageStore(uimage2DMS, ivec2, int, uvec4)0:254(1): error:    void imageStore(uimage2DMSArray, ivec3, int, uvec4)
</p>
</details>

**Comment by Despatra** [comment]
yeah you don't want to delete `rgba8`

**Comment by ThGrSoRu** [comment]
Same error.

**Comment by Despatra** [comment]
Hello again, turns out I need to change what version Optifine is using. It should be fixed next update.

**Comment by Despatra** [comment]
In case you see this I may not actually be able to switch away from images, I'm sorry that this won't work for you. It seems weirdly inconsistent with GPU's on weather or not it works
